title = "get-Moneyism"
[author]
name = "people for getmoneyism"
headline = "an anonymous collective of people supporting the get-moneyist vision"
bio = "The people for getmoneyism group is a collective supporting the goals and ideals of getmoneyism. Mostly made up of fit, social, and wealthy individuals who got that way through ignoring politics."

