copyright = "copyright People for Money 2024"
description = "Get-Moneyism, a new political philosophy based on self-improvement and personal effectiveness"
colorScheme = "blowfish"
[homepage]
layout = "hero"
showRecent = true
